### ISSUE TITLE
requiring the mean file

### ISSUE THREAD

**Issue by wangsiwei2010** [imatge-upc/sentiment-2016#2]
As do the Caffe running to predict the sentiment of a new picture , I'm desired to need the processing of trained pictures(the mean file of trained pictures). Would you like to give me a copy or a suggusting way?

**Comment by victorcampos7** [comment]
We used the mean from ILSVRC12 used in the pre-trained model. You can find it [here](https://github.com/BVLC/caffe/tree/master/python/caffe/imagenet).

**Comment by wangsiwei2010** [comment]
Thanks very much. I have found what I need.
