### ISSUE TITLE
what are these arguments?

### ISSUE THREAD

**Issue by GolaraRefahi** [imatge-upc/sentiment-2016#5]
I do not understand what is the arguments "output_path, output_files_prefix, files, models". Would you please help me in this regard?

**Comment by victorcampos7** [comment]
Can you point me to the concrete script or file you're having problems with?

**Comment by GolaraRefahi** [comment]
Thank you for your response. My main problem is “compare_and_plot_training_logs.py”

**Comment by victorcampos7** [comment]
The script parses and plots the logs generated by Caffe when training the models, and all these arguments have a help string that you can see in the [source code](https://github.com/imatge-upc/sentiment-2017-imavis/blob/master/compare_and_plot_training_logs.py#L32) or by running the script with `--help`.
